//
// Created by redha on 11/25/2022.
//

#ifndef CAVAIR_DISPLAYMODE_H
#define CAVAIR_DISPLAYMODE_H

typedef enum DisplayMode: unsigned char {
    DM_NONE,
    DM_TITLE,
    DM_SPLASH,
    DM_CO2_SELF_TEST,
    DM_CO2_SELF_TEST_SUCCESS,
    DM_CO2_SELF_TEST_FAILURE,

    DM_MAIN,
    DM_SYSTEM_INFO,
    DM_CO2_CONFIG,
    DM_CO2_CALIBRATION,
    DM_CO2_CALIBRATION_START,
    DM_CO2_CALIBRATION_COMPLETE,
    DM_CO2_CALIBRATION_FAILED,
    DM_CO2_CALIBRATION_CANCELLED,
    DM_SET_ALTITUDE,
    DM_SET_TEMP_OFFSET,
    DM_SETTING_TEMP_OFFSET_START,
    DM_SETTING_TEMP_OFFSET_COMPLETE,
    DM_SETTING_ALTITUDE_START,
    DM_SETTING_ALTITUDE_COMPLETE,
    DM_RESET_MINMAX,
    DM_RESET_MINMAX_START,
    DM_RESET_MINMAX_COMPLETE,
    DM_SET_UNITS,
    DM_SET_CO2_UNITS,
    DM_TEST_ALERTS,
    DM_FLASHLIGHT,
    DM_BATTERY_INFO,
} DisplayMode;

#endif //CAVAIR_DISPLAYMODE_H
